import type { Adapter, GeneratedFile, ResolvedConfig } from '../../types.js';

/**
 * GitHub Actions adapter.
 *
 * Generates a CI workflow that runs `vibecheck lint` as a PR check.
 * Also includes standard quality steps (lint, type-check, build, test).
 */
export const githubActionsAdapter: Adapter = {
  id: 'claude-code', // Uses same ID for internal purposes, identified by name
  name: 'GitHub Actions',
  enforcement: 'runtime',

  async generate(config: ResolvedConfig): Promise<GeneratedFile[]> {
    const workflow = generateWorkflow(config);
    return [
      {
        path: '.github/workflows/vibecheck.yml',
        content: workflow,
        mergeStrategy: 'create-only',
      },
    ];
  },
};

function generateWorkflow(config: ResolvedConfig): string {
  const activeRuleCount = Array.from(config.rules.values()).filter((r) => r.enabled).length;

  return `# Generated by VibeCheck — ${activeRuleCount} rules active
name: VibeCheck CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main, dev]

concurrency:
  group: \${{ github.workflow }}-\${{ github.ref }}
  cancel-in-progress: true

jobs:
  vibecheck:
    name: VibeCheck Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - run: npm ci
      - run: npx vibecheck lint --format github-actions

  quality:
    name: Code Quality
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - run: npm ci
      - run: npm run lint
      - run: npm run type-check

  build:
    name: Build
    needs: [quality]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - run: npm ci
      - run: npm run build

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - run: npm ci
      - run: npm test
`;
}
