import type { Adapter, GeneratedFile, ResolvedConfig } from '../../types.js';
import { getAllRules } from '../../engine/registry.js';

/**
 * Cursor adapter.
 *
 * Generates:
 * 1. .cursorrules — top-level rules summary
 * 2. .cursor/rules/<rule-id>.mdc — per-rule instruction files
 *
 * Enforcement is ADVISORY only — Cursor may choose to ignore these rules.
 */
export const cursorAdapter: Adapter = {
  id: 'cursor',
  name: 'Cursor',
  enforcement: 'advisory',

  async generate(config: ResolvedConfig): Promise<GeneratedFile[]> {
    const files: GeneratedFile[] = [];
    const allRules = getAllRules();
    const activeRules: Array<{ id: string; name: string; description: string; severity: string }> =
      [];

    for (const [ruleId, ruleConfig] of config.rules) {
      if (!ruleConfig.enabled) continue;
      const rule = allRules.get(ruleId);
      if (!rule) continue;

      activeRules.push({
        id: ruleId,
        name: rule.name,
        description: rule.description,
        severity: ruleConfig.severity,
      });

      // Generate per-rule .mdc file
      const mdcContent = generateRuleMdc(rule.id, rule.name, rule.description, ruleConfig.severity);
      const mdcPath = `.cursor/rules/${ruleId.replace('/', '-')}.mdc`;
      files.push({
        path: mdcPath,
        content: mdcContent,
        mergeStrategy: 'overwrite',
      });
    }

    // Generate top-level .cursorrules
    const cursorRules = generateCursorRules(activeRules);
    files.push({
      path: '.cursorrules',
      content: cursorRules,
      mergeStrategy: 'overwrite',
    });

    return files;
  },
};

function generateCursorRules(
  rules: Array<{ id: string; name: string; description: string; severity: string }>,
): string {
  const ruleLines = rules.map((r) => `- **${r.id}** (${r.severity}): ${r.description}`).join('\n');

  return `# VibeCheck Rules for Cursor

<!-- Generated by VibeCheck. Enforcement is advisory — -->
<!-- these rules guide AI behavior but cannot block operations. -->
<!-- For runtime enforcement, use Claude Code. -->

## Active Rules

${ruleLines}

## Guidelines

When writing or editing code in this project, follow these rules:

${rules.map((r) => `### ${r.name}\n${r.description}\n`).join('\n')}

These rules are enforced at runtime in Claude Code. In Cursor, please follow them as best practices.
`;
}

function generateRuleMdc(id: string, name: string, description: string, severity: string): string {
  // Determine glob pattern based on rule category
  let globs = '*';
  if (id.includes('import') || id.includes('deprecated') || id.includes('naming')) {
    globs = '*.{ts,tsx,js,jsx}';
  } else if (id.includes('migration')) {
    globs = '*.sql';
  }

  return `---
description: ${description}
globs: ${globs}
alwaysApply: ${severity === 'block'}
---

# ${name}

${description}

**Severity:** ${severity}

When writing code that matches this rule's scope, ensure compliance.
This rule is enforced at runtime in Claude Code with severity "${severity}".
`;
}
