import type { Adapter, GeneratedFile, ResolvedConfig } from '../../types.js';
import { getAllRules } from '../../engine/registry.js';

/**
 * Codex adapter.
 *
 * Generates:
 * 1. AGENTS.md — comprehensive rule documentation
 * 2. .codex/instructions.md — Codex-specific instructions
 *
 * Enforcement is ADVISORY only.
 */
export const codexAdapter: Adapter = {
  id: 'codex',
  name: 'Codex',
  enforcement: 'advisory',

  async generate(config: ResolvedConfig): Promise<GeneratedFile[]> {
    const allRules = getAllRules();
    const files: GeneratedFile[] = [];

    // Build AGENTS.md
    const sections: string[] = [
      '# Project Coding Guidelines',
      '',
      '<!-- Generated by VGuard. Enforcement is advisory — -->',
      '<!-- these rules guide AI behavior but cannot block operations. -->',
      '<!-- For runtime enforcement, use Claude Code. -->',
      '',
    ];

    // Group rules by category
    const categories = new Map<
      string,
      Array<{ id: string; name: string; desc: string; severity: string }>
    >();

    for (const [ruleId, ruleConfig] of config.rules) {
      if (!ruleConfig.enabled) continue;
      const rule = allRules.get(ruleId);
      if (!rule) continue;

      const category = ruleId.split('/')[0];
      const existing = categories.get(category) ?? [];
      existing.push({
        id: ruleId,
        name: rule.name,
        desc: rule.description,
        severity: ruleConfig.severity,
      });
      categories.set(category, existing);
    }

    for (const [category, rules] of categories) {
      sections.push(`## ${capitalize(category)} Rules`);
      sections.push('');
      for (const rule of rules) {
        sections.push(`### ${rule.name}`);
        sections.push(`**ID:** \`${rule.id}\` | **Severity:** ${rule.severity}`);
        sections.push('');
        sections.push(rule.desc);
        sections.push('');
      }
    }

    files.push({
      path: 'AGENTS.md',
      content: sections.join('\n'),
      mergeStrategy: 'overwrite',
    });

    // Build .codex/instructions.md — concise version for Codex's instruction system
    const instructionLines: string[] = [
      '<!-- Generated by VGuard — do not edit manually. -->',
      '<!-- Regenerate with: npx vguard generate -->',
      '',
      '# VGuard Coding Guidelines',
      '',
      'This project uses VGuard for AI coding guardrails. Follow these rules when writing code:',
      '',
    ];

    for (const [category, rules] of categories) {
      instructionLines.push(`## ${capitalize(category)}`);
      instructionLines.push('');
      for (const rule of rules) {
        instructionLines.push(`- **${rule.name}** [${rule.severity}]: ${rule.desc}`);
      }
      instructionLines.push('');
    }

    instructionLines.push('## Commands');
    instructionLines.push('');
    instructionLines.push('- `npx vguard lint` — scan for violations');
    instructionLines.push('- `npx vguard fix` — auto-fix violations');
    instructionLines.push('- `npx vguard doctor` — check configuration health');
    instructionLines.push('');

    files.push({
      path: '.codex/instructions.md',
      content: instructionLines.join('\n'),
      mergeStrategy: 'create-only',
    });

    return files;
  },
};

function capitalize(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1);
}
