import { writeFile, readFile, mkdir } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { join, dirname } from 'node:path';

import '../../presets/index.js';
import '../../rules/index.js';

import { discoverConfigFile, readRawConfig } from '../../config/discovery.js';
import { resolveConfig } from '../../config/loader.js';
import { getAllPresets } from '../../config/presets.js';
import { serializeConfig } from '../../config/compile.js';
import { bundleHookScript } from '../../eject/bundler.js';
import type { VGuardConfig, HookEvent, ResolvedConfig } from '../../types.js';

const HOOK_EVENTS: HookEvent[] = ['PreToolUse', 'PostToolUse', 'Stop'];

export async function ejectCommand(
  options: {
    adapter?: string;
    output?: string;
  } = {},
): Promise<void> {
  const projectRoot = process.cwd();
  const adapter = options.adapter ?? 'claude-code';
  const outputDir = options.output ?? join('.vguard', 'ejected');

  console.log('\n  VGuard Eject — Exporting standalone hooks...\n');
  console.log('  WARNING: After ejecting, hooks will NOT receive updates.');
  console.log('  You can safely remove VGuard from dependencies.\n');

  // Load config
  const discovered = discoverConfigFile(projectRoot);
  if (!discovered) {
    console.error('  No VGuard config found. Run `vguard init` first.');
    process.exit(1);
  }

  const rawConfig = await readRawConfig(discovered);
  const presetMap = getAllPresets();
  const resolvedConfig = resolveConfig(rawConfig as VGuardConfig, presetMap);

  // Generate bundled hook scripts
  for (const event of HOOK_EVENTS) {
    const script = bundleHookScript(event, resolvedConfig);
    const scriptPath = join(projectRoot, outputDir, `vguard-${event.toLowerCase()}.js`);
    await mkdir(dirname(scriptPath), { recursive: true });
    await writeFile(scriptPath, script, 'utf-8');
    console.log(`  Created ${scriptPath}`);
  }

  // Save frozen config
  const serialized = serializeConfig(resolvedConfig);
  const configPath = join(projectRoot, outputDir, 'frozen-config.json');
  await writeFile(configPath, JSON.stringify(serialized, null, 2), 'utf-8');
  console.log(`  Created ${configPath}`);

  // Generate eject readme
  const readmePath = join(projectRoot, outputDir, 'VGUARD-EJECTED.md');
  await writeFile(readmePath, generateEjectReadme(resolvedConfig, outputDir), 'utf-8');
  console.log(`  Created ${readmePath}`);

  // Auto-update .claude/settings.json if adapter is claude-code
  if (adapter === 'claude-code') {
    await updateClaudeSettings(projectRoot, outputDir);
  }

  console.log('\n  Ejected successfully.');
  if (adapter === 'claude-code') {
    console.log('  .claude/settings.json has been updated to use ejected hooks.');
  }
  console.log('  You can now remove VGuard from your dependencies.\n');
}

async function updateClaudeSettings(projectRoot: string, outputDir: string): Promise<void> {
  const settingsPath = join(projectRoot, '.claude', 'settings.json');

  let settings: Record<string, unknown> = {};
  if (existsSync(settingsPath)) {
    try {
      const raw = await readFile(settingsPath, 'utf-8');
      settings = JSON.parse(raw);
    } catch {
      settings = {};
    }
  }

  // Build hook entries pointing to ejected scripts
  const hooks: Record<string, unknown[]> = {};
  for (const event of HOOK_EVENTS) {
    const scriptPath = join(outputDir, `vguard-${event.toLowerCase()}.js`);
    hooks[event] = [
      {
        matcher: event === 'Stop' ? undefined : 'Edit|Write|Bash',
        hooks: [
          {
            type: 'command',
            command: `node ${scriptPath.replace(/\\/g, '/')}`,
          },
        ],
      },
    ];
  }

  settings.hooks = hooks;

  await mkdir(dirname(settingsPath), { recursive: true });
  await writeFile(settingsPath, JSON.stringify(settings, null, 2), 'utf-8');
  console.log(`  Updated ${settingsPath}`);
}

function generateEjectReadme(config: ResolvedConfig, outputDir: string): string {
  const ruleCount = Array.from(config.rules.values()).filter((r) => r.enabled).length;
  return `# VGuard — Ejected Hooks

These hook scripts were generated by \`vguard eject\` and are **self-contained**.
They do not require the \`@anthril/vguard\` npm package to run.

## What was exported

- **${ruleCount} active rules** bundled into standalone hook scripts
- **Frozen config** snapshot in \`frozen-config.json\`

## How to use

Your \`.claude/settings.json\` has been updated to point to these scripts.

Alternatively, configure manually:

\`\`\`json
{
  "hooks": {
    "PreToolUse": [{
      "hooks": [{ "type": "command", "command": "node ${outputDir.replace(/\\/g, '/')}/vguard-pretooluse.js" }],
      "matcher": "Edit|Write|Bash"
    }]
  }
}
\`\`\`

## Maintenance

These scripts are frozen — they will NOT receive updates when new VGuard versions
are released. To get updates, re-install VGuard and run \`vguard eject\` again.

## Generated

${new Date().toISOString()}
`;
}
